name: Update Leaderboard

on:
  pull_request:
    types:
      - closed

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests==2.31.0

      - name: Configure Git
        run: |
          git config --global user.email "lordtitan7@gmail.com"
          git config --global user.name "mlsanigeria"

      - name: Use a secret
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          
        run: |
          # Pass the API_TOKEN secret as an environment variable to your script
          python update_leaderboard.py

      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code || echo "::set-output name=changes::true"

      - name: Commit and Push Changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git pull
          git add LEADERBOARD.md README.md
          git commit -m "Update leaderboard"
          git remote set-url origin https://$API_TOKEN@github.com/mlsanigeria/AI-Hacktober-MLSA.git
          git push
